### ISSUE TITLE
Never ending loading when onEndReached and onStartReached are called simultaneously

### ISSUE THREAD

**Issue by mattproch** [GetStream/react-native-bidirectional-infinite-scroll#4] opened 2021-03-02 12:11 UTC
If both onEndReached and onStartReached are called at the same time (eg. the list of data is really short) the end loading indicator never stops loading.

**Video**

https://user-images.githubusercontent.com/20935135/109646003-ea683080-7b57-11eb-9de8-611acde53f20.mov

**Basic setup to reproduce:**

```
<FlatList
  data={[1, 2, 3]}
  renderItem={() => (
    <View style={{ marginBottom: 20, backgroundColor: '#102C1A', height: 100, width: '100%' }} />
  )}
  keyExtractor={(item) => item.toString()}
  onStartReached={loadPrevious}
  onStartReachedThreshold={0.2}
  onEndReached={loadAfter}
  onEndReachedThreshold={0.2}
/>
```

```
const loadPrevious = async () => {
  console.log('PREVIOUS START');

  return new Promise<any>((resolve) =>
    setTimeout(() => {
      console.log('PREVIOUS RESOLVE');
      resolve(null);
    }, 1000),
  );
};
```

```
const loadAfter = async () => {
  console.log('AFTER START');

  return new Promise<any>((resolve) =>
    setTimeout(() => {
      console.log('AFTER RESOLVE');
      resolve(null);
    }, 2000),
  );
};
```

**Comment by vishalnarkhede** [comment] 2021-03-02 14:46
@mattproch thanks for brining this up. I will take a look soon :)

**Comment by vaclavikjan** [comment] 2021-03-10 19:52
@vishalnarkhede, any update about this issue? Thanks!

**Comment by vishalnarkhede** [comment] 2021-03-10 20:19
@vaclavikjan I will take a look tomorrow :)

**Comment by vishalnarkhede** [comment] 2021-03-13 09:56
@vaclavikjan @mattproch Could you please try new patch that I just published? 0.3.2

**Comment by vishalnarkhede** [comment] 2021-03-20 10:11
Closing this for now. Please reopen if you still see the issue :)

**Closed by vishalnarkhede** 2021-03-20 10:11 UTC
Labels: resolved

**Comment by vaclavikjan** [comment] 2021-03-24 15:06
@vishalnarkhede, the issue is fixed. Thanks a lot!

**Comment by devvrat-sharma** [comment] 2022-09-03 17:29
I am facing this issue . Is it not resolved yet?
